In [3]:
import numpy as np

### Транспонирование

 Транспонированная матрица равна исходной матрице

In [4]:
>>> A = np.random.randint(-20, 70, (2, 2))
>>> print(A)
>>> R = (A.T).T
>>> print(R)

[[ 61  21]
 [ 18 -13]]
[[ 61  21]
 [ 18 -13]]


Транспоринование суммы матриц равно сумме транспонированных матриц

In [5]:
A = np.matrix('8 7 5; 5 4 3')
B = np.matrix('1 2 3; 7 7 7')
L = (A + B).T
R = A.T + B.T
print("Транспонирование суммы:\n",L)
print("Сумма транспонированных матриц:\n",R)

Транспонирование суммы:
 [[ 9 12]
 [ 9 11]
 [ 8 10]]
Сумма транспонированных матриц:
 [[ 9 12]
 [ 9 11]
 [ 8 10]]


Транспонирование произведения матриц равно произведению транспонированных матриц расставленных в обратном порядке

In [6]:
A = np.matrix('7 5; 7 4')
B = np.matrix('7 6; 7 7')
L = (A.dot(B)).T
R = (B.T).dot(A.T)
print("Транспонирование произведения матриц:\n",L)
print("Произведение транспонированных матриц расставленных в обратном порядке:\n",R)

Транспонирование произведения матриц:
 [[84 77]
 [77 70]]
Произведение транспонированных матриц расставленных в обратном порядке:
 [[84 77]
 [77 70]]


Транспонирование произведения матрицы на число равно произведению этого числа на транспонированную матрицу

In [7]:
A = np.matrix('1 2 3; 4 5 6')
k = 70
L = (k * A).T
R = k * (A.T)
print("Транспонирование произведения матрицы на число:\n",L)
print("Произведение этого числа на транспонированную матрицу:\n",R)

Транспонирование произведения матрицы на число:
 [[ 70 280]
 [140 350]
 [210 420]]
Произведение этого числа на транспонированную матрицу:
 [[ 70 280]
 [140 350]
 [210 420]]


Определители исходной и транспонированной матрицы совпадают

In [8]:
A = np.matrix('55 100; 1 5')
A_det = np.linalg.det(A)
A_T_det = np.linalg.det(A.T)
print("Определитель исходной матрицы:",format(A_det, '.9g'))
-2
print("Определитель транспонированной матрицы:",format(A_T_det, '.9g'))

Определитель исходной матрицы: 175
Определитель транспонированной матрицы: 175


### Умножение 

 Произведение единицы и любой заданной матрицы равно заданной матрице

In [9]:
A = np.matrix('1 2; 3 4')
L = 1 * A
print("Матрица умноженная на единицу:\n", L)

Матрица умноженная на единицу:
 [[1 2]
 [3 4]]


Произведение нуля и любой матрицы равно нулевой матрице, размерность которой равна исходной матрицы

In [10]:
A = np.matrix('1 2; 3 4')
L = 0 * A
print("Произведение матрицы на ноль:\n", L)

Произведение матрицы на ноль:
 [[0 0]
 [0 0]]


Произведение матрицы на сумму чисел равно сумме произведений матрицы на каждое из этих чисел

In [11]:
A = np.matrix('1 2; 1 2')
p = 70
q = 5
L = (p + q) * A
R = p * A + q * A
print("Произведение матрицы на сумму чисел:\n", L)
print("Сумма произведений матрицы на каждое из этих чисел:\n", R)

Произведение матрицы на сумму чисел:
 [[ 75 150]
 [ 75 150]]
Сумма произведений матрицы на каждое из этих чисел:
 [[ 75 150]
 [ 75 150]]


Произведение матрицы на произведение двух чисел равно произведению второго числа и заданной матрицы, умноженному на первое число

In [12]:
A = np.matrix('1 2; 1 2')
p = 5
q = 100
L = (p * q) * A 
R = p * (q * A)
print("Произведение матрицы на произведение двух чисел:\n", L)
print("Произведение второго числа и заданной матрицы, умноженному на первое число:\n", R)

Произведение матрицы на произведение двух чисел:
 [[ 500 1000]
 [ 500 1000]]
Произведение второго числа и заданной матрицы, умноженному на первое число:
 [[ 500 1000]
 [ 500 1000]]


Произведение суммы матриц на число равно сумме произведений этих матриц на заданное число

In [13]:
A = np.matrix('1 2; 1 2')
B = np.matrix('3 4; 5 5')
k = 100
L = k * (A + B)
R = k * A + k * B
print("Произведение суммы матриц на число:\n", L)
print("Сумма произведений этих матриц на заданное число:\n", R)

Произведение суммы матриц на число:
 [[400 600]
 [600 700]]
Сумма произведений этих матриц на заданное число:
 [[400 600]
 [600 700]]


### Сложение

Коммутативность сложения. От перестановки матриц их сумма не изменяется

In [14]:
A = np.matrix('1000 2000; 300 400')
B = np.matrix('500 600; 7000 8000')
L = A + B
R = B + A
print("Сумма А + В:\n", L)
print("Сумма В + А:\n", R)

Сумма А + В:
 [[1500 2600]
 [7300 8400]]
Сумма В + А:
 [[1500 2600]
 [7300 8400]]


Ассоциативность сложения. Результат сложения трех и более матриц не зависит от порядка, в котором эта операция будет выполняться

In [15]:
A = np.matrix('1 1; 1 1')
B = np.matrix('2 2; 2 2')
C = np.matrix('3 3; 3 3')
L = A + (B + C)
R = (A + B) + C
print("Сумма A + (B + C):\n", L)
print("Сумма (A + B) + C:\n", R)

Сумма A + (B + C):
 [[6 6]
 [6 6]]
Сумма (A + B) + C:
 [[6 6]
 [6 6]]


Для любой матрицы существует противоположная ей, такая, что их сумма является нулевой матрицей

In [16]:
A = np.matrix('20000000 30000000; 40000000 50000000')
L = A + (-1)*A
print("Нулевая матрица:\n", L)

Нулевая матрица:
 [[0 0]
 [0 0]]


### Умножение матриц

Ассоциативность умножения. Результат умножения матриц не зависит от порядка, в котором будет выполняться эта операция

In [17]:
A = np.matrix('1 1; 1 1')
B = np.matrix('2 2; 2 2')
C = np.matrix('5 5; 5 5')
L = A.dot(B.dot(C))
R = (A.dot(B)).dot(C)
print("Произведение A * (B * C):\n", L)
print("Произведение (A * B) * C:\n", R)

Произведение A * (B * C):
 [[40 40]
 [40 40]]
Произведение (A * B) * C:
 [[40 40]
 [40 40]]


Дистрибутивность умножения. Произведение матрицы на сумму матриц равно сумме произведений матриц

In [18]:
A = np.matrix('1 1; 1 1')
B = np.matrix('2 2; 2 2')
C = np.matrix('5 5; 5 5')
L = A.dot(B + C)
R = A.dot(B) + A.dot(C)
print("Произведение A * (B + C):\n", L)
print("Произведение A * B + A * C:\n", R)

Произведение A * (B + C):
 [[14 14]
 [14 14]]
Произведение A * B + A * C:
 [[14 14]
 [14 14]]


Умножение матриц в общем виде не коммутативно. Это означает, что для матриц не выполняется правило независимости произведения от перестановки множителей

In [19]:
A = np.matrix('1 5; 10 1')
B = np.matrix('5 2; 2 12')
L = A.dot(B)
R = B.dot(A)
print("Произведение A * B:\n", L)
print("Произведение B * A:\n", R)

Произведение A * B:
 [[15 62]
 [52 32]]
Произведение B * A:
 [[ 25  27]
 [122  22]]


Произведение заданной матрицы на единичную равно исходной матрице

In [20]:
A = np.matrix('5 4; 1 8')
E = np.matrix('1 0; 0 1')
L = E.dot(A)
R = A.dot(E)
print("Произведение заданной матрицы на единичную:\n", L)
print("Произведение единичной матрицы на заданную:\n", R)
print("Исходная матрица:\n", A)

Произведение заданной матрицы на единичную:
 [[5 4]
 [1 8]]
Произведение единичной матрицы на заданную:
 [[5 4]
 [1 8]]
Исходная матрица:
 [[5 4]
 [1 8]]


Произведение заданной матрицы на нулевую матрицу равно нулевой матрице

In [21]:
A = np.matrix('5 4; 1 8')
Z = np.matrix('0 0; 0 0')
L = Z.dot(A)
R = A.dot(Z)
print("Произведение заданной матрицы на нулевую:\n", L)
print("Произведение нулевой матрицы на заданную:\n", R)
print("Исходная матрица:\n", Z)

Произведение заданной матрицы на нулевую:
 [[0 0]
 [0 0]]
Произведение нулевой матрицы на заданную:
 [[0 0]
 [0 0]]
Исходная матрица:
 [[0 0]
 [0 0]]


### Определитель матрицы

Определитель матрицы остается неизменным при ее транспонировании

In [22]:
A = np.matrix('1 10 2; 10 2 -1; 5 8 11')
R = A.T
det_A = round(np.linalg.det(A), 3)
det_R = round(np.linalg.det(R), 3)
print("Опеределитель матрицы:", det_A)
print("Определитель транспонированной матрицы:", det_R)

Опеределитель матрицы: -980.0
Определитель транспонированной матрицы: -980.0


Если у матрицы есть строка или столбец, состоящие из нулей, то определитель такой матрицы равен нулю

In [23]:
A = np.matrix('1 10 2; 0 0 0; 5 8 11')
print("Опеределитель матрицы:", np.linalg.det(A))

Опеределитель матрицы: 0.0


При перестановке строк матрицы знак ее определителя меняется на противоположный

In [24]:
A = np.matrix('1 10 2; 10 2 -1; 5 8 11')
B = np.matrix('10 2 -1; 1 10 2; 5 8 11')
R = round(np.linalg.det(A), 3)
L = round(np.linalg.det(B), 3)
print("Определитель матрицы А:", R)
print("Определитель матрицы В:", L)

Определитель матрицы А: -980.0
Определитель матрицы В: 980.0


Если у матрицы есть две одинаковые строки, то ее определитель равен нулю

In [25]:
A = np.matrix('1 10 2; 1 10 2; 5 8 11')
R = round(np.linalg.det(A), 3)
print("Определитель матрицы А:", R)

Определитель матрицы А: 0.0


Если все элементы строки или столбца матрицы умножить на какое-то число, то и определитель будет умножен на это число

In [26]:
A = np.matrix('1 10 2; 1 11 2; 5 8 11')
k = 100
B[2, :] = k * B[2, :]
det_A = round(np.linalg.det(A), 3)
det_B = round(np.linalg.det(B), 3)
print("Опеределитель матрицы:", det_A)
print("Определитель матрицы умноженной на число:", det_B)

Опеределитель матрицы: 1.0
Определитель матрицы умноженной на число: 98000.0


Если все элементы строки или столбца можно представить как сумму двух слагаемых, то определитель такой матрицы равен сумме определителей двух соответствующих матриц

In [27]:
A = np.matrix('-1 -1 3; -1 -1 3; 2 2 3')
B = np.matrix('-1 -1 3; 2 2 7; 2 2 3')
C = A.copy()
C[1, :] += B[1, :]
R = round(np.linalg.det(C), 3)
L = round(np.linalg.det(A), 3) + round(np.linalg.det(B), 3)
print("Определитель матрицы C:", R)
print("Определитель суммы двух матриц:", L)

Определитель матрицы C: 0.0
Определитель суммы двух матриц: 0.0


Если к элементам одной строки прибавить элементы другой строки, умноженные на одно и тоже число, то определитель матрицы не изменится

In [28]:
A = np.matrix('-1 -1 3; -1 0 3; 2 2 3')
k = 70
B = A.copy()
B[1, :] = B[1, :] + k * B[0, :]
R = round(np.linalg.det(A), 3)
L = round(np.linalg.det(B), 3)
print("Определитель матрицы A:", R)
print("Определитель матрицы B:", L)

Определитель матрицы A: -9.0
Определитель матрицы B: -9.0


Если строка или столбец матрицы является линейной комбинацией других строк (столбцов), то определитель такой матрицы равен нулю

In [29]:
A = np.matrix('-3 -1 5; -1 0 3; 2 2 3')
k = 70
A[1, :] = A[0, :] + k * A[2, :]
R = round(np.linalg.det(A), 3)
print("Определитель матрицы A:", R)

Определитель матрицы A: 0.0


Если матрица содержит пропорциональные строки, то ее определитель равен нулю

In [30]:
A = np.matrix('-3 -1 5; -1 0 3; 2 2 3')
k = 70
A[1, :] = k * A[0, :]
R = round(np.linalg.det(A), 3)
print("Определитель матрицы A:", R)

Определитель матрицы A: 0.0


### Обратная матрица

Обратная матрица обратной матрицы есть исходная матрица

In [31]:
A = np.matrix('8. -7.; 5. 4.')
A_inv = np.linalg.inv(A)
A_inv_inv = np.linalg.inv(A_inv)
print("Определитель исходной матрицы:\n", A_inv)
print("Определитель обратной обратной матрицы A:\n", A_inv_inv)

Определитель исходной матрицы:
 [[ 0.05970149  0.10447761]
 [-0.07462687  0.11940299]]
Определитель обратной обратной матрицы A:
 [[ 8. -7.]
 [ 5.  4.]]


Обратная матрица транспонированной матрицы равна транспонированной матрице от обратной матрицы

In [32]:
A = np.matrix('8. -7.; 5. 4.')
L = np.linalg.inv(A.T)
R = (np.linalg.inv(A)).T
print("Обратная матрица транспонированной матрицы:\n",L)
print("Транспонированная матрица от обратной матрицы:\n", R)

Обратная матрица транспонированной матрицы:
 [[ 0.05970149 -0.07462687]
 [ 0.10447761  0.11940299]]
Транспонированная матрица от обратной матрицы:
 [[ 0.05970149 -0.07462687]
 [ 0.10447761  0.11940299]]


Обратная матрица произведения матриц равна произведению обратных матриц

In [33]:
A = np.matrix('8. -7.; 5. 4.')
B = np.matrix('15. -7.; 22. 2.')
L = np.linalg.inv(A.dot(B))
R = np.linalg.inv(B).dot(np.linalg.inv(A))
print("Обратная матрица произведения матриц:\n",L)
print("Произведение обратных матриц:\n", R)

Обратная матрица произведения матриц:
 [[-0.00219014  0.00567813]
 [-0.01322193 -0.00275795]]
Произведение обратных матриц:
 [[-0.00219014  0.00567813]
 [-0.01322193 -0.00275795]]
